<?php

/**
 * Class PDFBuilder
 *
 * <p>
 * This class is an extension of the pdf class
 * from {@see http://fpdf.de/}. It is used to auto-generate the
 * risk analysis result as PDF, using the scan reports of the
 * tools of the bundle.
 * </p>
 *
 * @author David Dewes <hello@david-dewes.de>
 */
class PDFBuilder extends FPDF
{
    /**
     * PDFBuilder constructor.
     *
     * @param string $orientation
     * @param string $unit
     * @param string $size
     */
    function __construct($orientation = 'P', $unit = 'mm', $size = 'A4')
    {
        parent::__construct($orientation, $unit, $size);
    }

    /**
     * Build the PDF Header (automatically used)
     */
    function Header()
    {
        parent::Header(); // TODO: Change the autogenerated stub
    }

    /**
     * Build the PDF Footer (automatically used)
     */
    function Footer()
    {
        parent::Footer(); // TODO: Change the autogenerated stub
    }
}